### ISSUE TITLE
Inform Forks on key change

### ISSUE THREAD

**Issue by feeds** [Baschdl/match4healthcare#478]
Since we keep our mapbox_token private now, we should update our forks via the secrity alert feature on GitHub that we are changing our key in 7-14 days.

**Comment by kevihiiin** [comment]
Once we have merged PR 477 I will notify our forks:)

**Comment by kevihiiin** [comment]
Took some time to delete the pull request from the private fork inside the security advisory because it vanished (error 404). But thankfully the support was fast and deleted it for us :)
Our first security advisory is now public https://github.com/match4everyone/match4healthcare/security/advisories/GHSA-9p59-9j8h-93cq

- - - 
Edit:
If I understood the concept correctly, GitHub will manually check our advisory (takes up to 72h) and if they think it is a valid one they will inform our forks automatically. If not I will manually create an issue with on our forks

**Comment by kevihiiin** [comment]
GitHub does not automatically inform forks, it only informs projects that depend on ours. The support told me they forwarded the idea to their development team but for now we should inform forks manually.

I cannot creates an issue on most of the forks and the one fork were I can does not use the map function. 

=> Issue resolved. We need to rotate the key internally and use another one when we deploy the next time
